### ISSUE TITLE
Bug in file system initialization

### ISSUE THREAD

**Issue by hayley-leblanc** [NVSL/PMFS-new#4]
Hi,

I'm not sure if this repo is still maintained, but I have a bug to report in the `pmfs_init()` function in super.c. When the directory entries in the root directory are set up around line 452, the "." entry is never explicitly flushed to PM. If the system loses power before this entry becomes durable, the root directory is inaccessible on the next mount and attempting to `ls` it causes the fs to hang. This issue is fixed by adding one flush after setting the values of this entry; I can submit a PR with a patch in a bit.

**Comment by Andiry** [comment]
I think ".." entry is flushed, but "." seems not. So this does look like a
bug to me. PR is welcome.
